export default {
    '11d': 'Cloud-Lightning.svg',		
    '09d': 'Cloud-Drizzle.svg',
    '10d': 'Cloud-Rain.svg',
    '13d': 'Cloud-Rain.svg',
    '09d': 'Cloud-Rain.svg',
    '13d': 'Cloud-Snow.svg',
    '50d': 'Cloud-Fog.svg',
    '01d': 'Sun.svg',
    '01n': 'Moon.svg',
    '02d': 'Cloud-Sun.svg',
    '02n': 'Cloud-Moon.svg',
    '03d': 'Cloud.svg',
    '03n': 'Cloud.svg',
    '04d': 'Cloud.svg',
    '04n': 'Cloud.svg',
}